title = "Datadelico"
baseURL = "https://datadelico.com"
languageCode = "es"
theme = 'ananke'
resourceDir = "../resources"

DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 3 # esto se establece en un número bajo para mostrar con contenido ficticio. Establezcalo en un número más alto
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.es]
    title = "Datadelico"
    weight = 1
    contentDir = "content/"
    # languageDirection = 'rtl' para lenguas de derecha a izquierda

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "fff"
  author = "Esteban"
  favicon = ""
  site_logo = ""
  description = "Datadelico podría ser un espacio en el que se exploran los aspectos más misteriosos y fascinantes de los datos."
  # selecciona un color de fondo de cualquiera de esta página: https://tachyons.io/docs/themes/skins/ y prefícialo con "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/datadelico"
